### ISSUE TITLE
VisualVM 1.3.9 Mac OS X Package is malformed for a platform application

### ISSUE THREAD

**Issue by wadechandler** [visualvm/visualvm.src#11]
I downloaded the most recent, at least per the home page, 1.3.9, as a Mac `.dmg` installer. I ran it, dragged the app to the `Applications` icon in the installer, and it copied it over. When I tried to run it, Mac OS gave me a dialog that the application was corrupted, and I needed to install it. I had already went to edit `visualvm.conf` to increase the RAM as I planned to analyze a large heap immediately.

I thought things looked odd compared to a standard NB RCP/platform layout. I ran from the CLI, from bin, and it showed it could not find the clusters file. After further investigation I noticed that the `platform`, `profiler`, and `visualvm` directories were under `Contents` versus `Resources`.

I then copied those directories to their place under `Resources`, and then the app started. This is still slightly different from a standard layout which usually has a folder under the Mac app directory of the same name in my experience, but at least this is running.

**Comment by wadechandler** [comment]
Well, it sort of runs. It runs since I know how to run it from the CLI from the Mac installed directory, but if I try to run it from the Mac application launcher, the OS says it is corrupt. This is inherently different than the way this works with a NetBeans install. I got this message before, and is why I moved the cluster directories in the first place, after things failing to run from the CLI. So, I think there is still something different about the packaging as I have been able to change the memory before. Anyways, pointers welcome, just giving you what I have here.

**Comment by thurka** [comment]
Application is signed, so you cannot change it. It means you cannot modify `visualvm.conf` file inside of VisualVM.app folder. If you need to add JVM options, you can use `${userdir}/etc/visualvm.conf` file and use something like `visualvm_default_options="-J-Xmx800m ${visualvm_default_options}"`

**Comment by wadechandler** [comment]
Makes sense, thanks Tomas. The other issues with not being able to run from the CLI are still there however; if one tries to run the `*/bin/visualvm` file where as NetBeans itself can run this way fine. This seems related to the structure I mentioned. Thanks again.

**Comment by thurka** [comment]
I am able to run VisualVM 1.3.9 from commandline. For example I used this line:
`thurka$ ./VisualVM.app/Contents/MacOS/visualvm --jdkhome ~/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`

**Comment by thurka** [comment]
It looks like this problem is solved. Closing.
