### ISSUE TITLE
VisualVM 1.3.9 on macOS doesn't start

### ISSUE THREAD

**Issue by MrBuddyCasino** [visualvm/visualvm.src#13]
I get the following error dialogs:
"Cannot load even default layout, using internally predefined configuration"
"Cannot load window system persistent data, user directory content is broken. Resetting to default layout..."

Java version: 1.8.0_51

Is this a known bug?

**Comment by thurka** [comment]
Please attach VisualVM messages.log file. This file is here: `~/Library/Application\ Support/VisualVM/1.3.9/var/log/messages.log`

**Comment by MrBuddyCasino** [comment]
Attached.
[messages.txt](https://github.com/visualvm/visualvm.src/files/774815/messages.txt)

**Comment by thurka** [comment]
Thanks for the messages.log file. The following lines from your file:
_>System Info: 
  Product Version         = VisualVM 1.3.9
  Operating System        = Mac OS X version 10.12.3 running on x86_64
  Java; VM; Vendor        = 9-ea; Java HotSpot(TM) 64-Bit Server VM 9-ea+155; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 9-ea+155_

clearly shows that you are running VisualVM on JDK 9-ea build 155 and not on JDK 1.8.0_51.

**Comment by MrBuddyCasino** [comment]
God I feel stupid, sorry for wasting your time. I had removed the Java 9 JRE, but not the JDK it seems.
To the poor souls that will undoubtedly have the same issue, this is the cause:

VisualVM uses "/usr/libexec/java_home" to resolve a JVM which is a binary that apparently gives a "best match", and just returns the newest one when in doubt.
The terminal can give you a different $JAVA_HOME or "java -version", they are not related at all.
It seems the only way to fix this is to delete the incompatible JVM.

**Comment by thurka** [comment]
> It seems the only way to fix this is to delete the incompatible JVM.

This is not true. You can tell VisualVM, which JDK to use. There are two possibilities.
1. If you are starting VisualVM from commandline, you can use the following options: `thurka$ ./VisualVM.app/Contents/MacOS/visualvm --jdkhome ~/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
2. If you want to make this change permanent, create `~/Library/Application Support/VisualVM/1.3.9/etc/visualvm.conf` file. Its content should look like this: `visualvm_jdkhome=~/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`

**Comment by thurka** [comment]
Closing.
