### ISSUE TITLE
Can not get CPU usage of local process nor sample the process

### ISSUE THREAD

**Issue by DaGeRe** [visualvm/visualvm.src#8]
When I start an java process, nevertheless whether I do it directly, via maven or via eclipse, I can not monitor CPU usage nor sample the process.

I've started visualvm with visualvm --jdkhome /usr/lib/jvm/java-8-openjdk-amd64/ and am running visualvm 1.3.8 installed from ubuntu 16.10 latest repository. I have no other jvm installed, so I assume they are running on the same vm (update-alternatives does only return this one java-installation).

When I try to sample the same process with the latest version from git, which I've cloned and I am running with ant run, I can see the CPU and start sampling. 

Is this a known issue, or is there an configuration which I could add to my package-installed visualvm?

**Comment by thurka** [comment]
Please attach VisualVM messages.log file. This file is here: `~/.visualvm/1.3.8/var/log/messages.log`

**Comment by DaGeRe** [comment]
I've done a rm ~/.visualvm/* -rf in order to get a clean messages-file, and now I can see the cpu usage again. I'll report if it appears again.

**Comment by thurka** [comment]
Ok, thanks for info.
